### ISSUE TITLE
Baubles Update Breaks Everything

### ISSUE THREAD

**Issue by nephatrine** [M4thG33k/TombManyGraves#21]
Updating to Azanor's latest Baubles "beta" releases (required by the latest Botania update) means that no one can respawn once dead - the client crashes and on reconnect they're stuck in limbo. 

```
[16:06:42] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerEvent$Clone@39d9f49e:
java.lang.NoClassDefFoundError: baubles/common/lib/PlayerHandler
        at com.m4thg33k.tombmanygraves.core.handlers.DeathInventory.<init>(DeathInventory.java:51) ~[DeathInventory.class:?]
        at com.m4thg33k.tombmanygraves.core.handlers.DeathInventoryHandler.getDeathList(DeathInventoryHandler.java:81) ~[DeathInventoryHandler.class:?]
        at com.m4thg33k.tombmanygraves.core.events.TombManyGravesCommonEvents.onPlayerClone(TombManyGravesCommonEvents.java:226) ~[TombManyGravesCommonEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_508_TombManyGravesCommonEvents_onPlayerClone_Clone.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:431) [ForgeEventFactory.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71049_a(EntityPlayer.java:2153) [zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71049_a(EntityPlayerMP.java:1008) [lu.class:?]
        at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:529) [mp.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:1068) [me.class:?]
        at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:31) [in.class:?]
        at net.minecraft.network.play.client.CPacketClientStatus.func_148833_a(SourceFile:8) [in.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by M4thG33k** [comment]
A new update went live 20 minutes ago.

**Comment by nephatrine** [comment]
Wow, nevermind then! It hadn't posted to Curse when I first started opening the issue so I hadn't seen it. That's fantastic!

**Comment by M4thG33k** [comment]
No problem! ^_^

**Comment by UnNinja** [comment]
I am still experiencing this problem in multiplayer, even with the latest version of TMG
