### ISSUE TITLE
Server crash on 2.1.13

### ISSUE THREAD

**Issue by chris54721** [M4thG33k/TombManyGraves#28]
**Mod version:** 2.1.13 (All the Mods modpack)
**Crash log:** http://hastebin.com/afutoxehin

**Relevant stacktrace:**

```
java.lang.NullPointerException
        at com.m4thg33k.tombmanygraves.tiles.TileDeathBlock.hasSoulboundEnchantment(TileDeathBlock.java:786) ~[TileDeathBlock.class:?]
        at com.m4thg33k.tombmanygraves.tiles.TileDeathBlock.isValidForGrave(TileDeathBlock.java:165) ~[TileDeathBlock.class:?]
        at com.m4thg33k.tombmanygraves.tiles.TileDeathBlock.copyInventoryWithoutSoulbound(TileDeathBlock.java:804) ~[TileDeathBlock.class:?]
        at com.m4thg33k.tombmanygraves.tiles.TileDeathBlock.getInventorySansSoulbound(TileDeathBlock.java:818) ~[TileDeathBlock.class:?]
        at com.m4thg33k.tombmanygraves.core.handlers.DeathInventory.<init>(DeathInventory.java:45) ~[DeathInventory.class:?]
        at com.m4thg33k.tombmanygraves.core.handlers.DeathInventoryHandler.createDeathInventory(DeathInventoryHandler.java:35) ~[DeathInventoryHandler.class:?]
        at com.m4thg33k.tombmanygraves.core.events.TombManyGravesCommonEvents.onPlayerDeath(TombManyGravesCommonEvents.java:80) ~[TombManyGravesCommonEvents.class:?]
```

**Comment by M4thG33k** [comment]
I'll try to look into this later this week, but can't guarantee anything. School/other projects have taken a higher priority at the moment. :-/
